#!/bin/bash

# Update Git submodules
/workspaces/hw-jjjay41223212/downloadsgit submodule update --init

# Install Python packages using pip
pip install flask flask_cors bs4 lxml pelican markdown gevent

# Optionally, you can add more commands or customizations here.

